### ISSUE TITLE
Projekt - zarządzanie

### ISSUE THREAD

**Issue by Triloworld** [vuejs-pl/vuejs.org#1]
Zacznijmy od priorytetów i od taska per strona dla tego repozytorium jako najważniejszego

Propozycja:
Na ten moment utworzymy kilkanaście zadań odnośnie części związanej z nawigacją, podpowiedziami i elementami nie będącymi częścią samej treści strony.

Dodatkowo przetłumaczyć w pełni stronę główną.

**Comment by jakex7** [comment]
Nieaktualne.
