### ISSUE TITLE
Przetłumaczenie strony vuejs.org

### ISSUE THREAD

**Issue by Triloworld** [vuejs-pl/vuejs.org#13]
Te zadanie odnosi się do elementów będących częścią całej strony vuejs.org i niebędących treścią. 
Przykład: Nawigacja, Tekst w atrybucie ALT pod logiem etc. 
Są to drobne elementy wyświetlane na więcej niż jednej stronie

**Comment by jakex7** [comment]
Wykonane w pull request #20
