### ISSUE TITLE
Ustawienia dla organizacji

### ISSUE THREAD

**Issue by Triloworld** [vuejs-pl/vuejs.org#14]
Potrzebujemy nowego loga.
Profil wymaga aktualizacji o dane.
Tłumaczenie dla : https://github.com/orgs/pl-vuejs/topics
Projekt na poziomie organizacji do zarządzania wszystkimi zadaniami i ich kolejkowaniem.
Dodanie strony i opisu tak jak oni mają : https://github.com/vuejs

**Comment by wbankowski** [comment]
Masz jakiś inny pomysł na logo? Może zmienimy kolory z logo Vue na nasze narodowe biało czerwone?

**Comment by Triloworld** [comment]
To jest dobry pomysł aczkolwiek samego logo nie chciałbym ruszać.
Pomysł jest taki by dodać biało-czerwone tło
