### ISSUE TITLE
[Update] for main repo

### ISSUE THREAD

**Issue by mbiesiad** [vuejs-pl/vuejs.org#28]
Hi All!

This [PR](https://github.com/vuejs/vuejs.org/pull/2665) is about to add this Polish repo for README on the main site. 🔥 
Great job!

Best wishes,

**Comment by jakex7** [comment]
We have been trying to get there some time ago, it's required to increase the translated pages. But maybe it will work this time 😉

**Comment by jakex7** [comment]
You can add `Primary maintainer - [Jakub Grzywacz (jakex7)](https://github.com/jakex7)` like in others translations to make it easier to contact. 👌

**Comment by mbiesiad** [comment]
@jakex7 ok sure, great idea! keep in touch
